language: node_js
node_js:
- 10.8.0
cache:
  directories:
  - node_modules
install:
- npm install
- npm install -g typescript
script:
- npm test
notifications:
  email: false
before_deploy:
- npm install --production
deploy:
  provider: npm
  email: tim@timcole.me
  api_key:
    secure: kBE+hGBJQXpSWWQzY7ldwX0W2HVBHg6onPhJGn+w8bvmejmwzVhV9FM6Ca7w3z0i2gfITesnttZKV9XIE/abZ5YxSHbg+/ra6O2lgecR5mMBAmx3W5AZqiehPfQFtTKJJAeda14IDZHSZ8BGeLQ/mtsY+3oGhPEWf33KHv9Ncuv4djwYcItja3FzE/s2Y9nCK8833GL7n7a+MpF1mUThaDBWlLqBijFSPf0UpDKxpbJyk5fXxqb36KR8/y19qnXsu44Yxeb8l+N5OXIMr3iXwYn7s/0SdPWyZaCv950CSaHgCsWIM+GsLi8FHwPEXPhaSWv4ugyWGRCakNdrMYnrNbr3Xbyh4hyLo7ufsUKtFL1JZDJt3GSP7UMurKdDiBLlmZeN7uXU4GH9ZlHALiJ19N2NTskYTNF+7aYxpnl8A/IwrXnitAyCygVkRQNWyE4301MEnuMKB2ezw1I7L1bl0JMDexXS0PFK/iaDJgf+hJiHu+i1K559DlzlNn/42yEBl4nmPTHSwo+gC4JLW5aRLS2Nuv4i9BykFH8tUMejfR0LHvVzWkY4Acel5PwVCjkwBjsuMgFZQDNEm49Ak+JN9FSQRiNFVEM9SWCQU4r9YRuLXIyALX+muZjzxh0t6rY1m1nBhMy9SMjbZpkIzS0eR/B3erasgtxWjAfclYkMZvE=
  skip_cleanup: true
  on:
    repo: TimothyCole/socialblade-js
    branch: master
