language: node_js
node_js:
  - 10.8.0
cache:
  directories:
  - node_modules
install:
- npm install
- npm install -g typescript
script:
- npm test
notifications:
  email: false

before_deploy:
  - npm install --production
deploy:
  provider: npm
  email: tim@timcole.me
  api_key:
    secure: npEyAIyKZugFU01uyviotNt6wjIdMlGcLwNeuZVkUWxlIMrUHw4TeAaONbb+uB3DjKSRlpU+GjE4hkyYu1sQK4hRizH/fzYDeL96HLJhsFUBvnUnTt6cn8lEO7snlYVDBQ2sux9lprrugjQyMVJJXjjA3TJvLHUx6ym5O+XjCVUnq09PFdiFFAdR2VONQ3f5HB2EweoDCF2Zy4JjfUb5G6yDEHAejyH6wa6FaTo9a8suEiy7CLePwwV5MTAkG8DC0h2nlmyoSvWgDFqtI4uRq8neNJih6RRpkyZkLZP5hmDcrZAhntArsnz43Z89fiIMHxPYUb4nadEG0Nslx3ExhsOYs/1D9MUNEDOXyAgxOtJmjrX6ux3grwSk8W88G8kS7WV86R+FRjTBsyro56NV7/VL4OVFm55jkgoFFD0DtSejgG/6+kumtJvpoR1vaVl+bCTs4fnENtw3LsjiRhMOoOG+0I8532unQbl29KSUPpey91XgDVwDq7x35GG2KY6R8uMxQCy44tqU2/uwZ7mu7Li07G5Ieelc8V4HdTdbGroXqVg2DyTlh+a6mz6EI3Qn8o/yjGqYeo2+b8U9vrrX7emfkuFwwPkYyk/2kC+CQLn+oM7Y0698PlGkxKDQPGF5F8oDoEnZLidphtf1O0ufFv+Sbc1ezvgM5g4NI/gDKeg=
  skip_cleanup: true
  on:
    repo: TimothyCole/socialblade-js
    branch: master
