language: node_js
node_js:
- 10.8.0
cache:
  directories:
  - node_modules
install:
- npm install
- npm install -g typescript
script:
- npm test
notifications:
  email: false
before_deploy:
- npm install --production
deploy:
  provider: npm
  email: tim@timcole.me
  api_key:
    secure: nM2qN3Lqo7SNymcNjsyZw67V3RVJx6zxpiiHl+457Riw49I9hXVnZvlC3STGyHKw/xxMEXcTYxjfhg1ZuyumvfpLUPdQT6lH0eb3jbzbVzN91sPZwHCtMmnvRjfunliCDz37U0t/SEd3orvDDOQSqhReNY7+mM2H7Zy+l5lK6XUN8lhqBkdnOhOzPGt6zkOqn30n8/BPXSFSwwFpQ2uVSoPpgFjx/ZhFQOdHeQdzBZZ3PniBjZKXldBoUcjeOLT5iYqvTjdfUTBs0httexwHUXc500ALS+J9sUyjTcDoabVosPg3sYEmCjf1G3cQi90a6gtNzxs56mJGJPLSoaKNXvOwNWP4hy3v7irdrN8kjH2F+LYUTVbtXANGvCQXcuRc20o8rtHQzOvD5AAX5zYXvt42rPN2wBeJg7pLF15QNkDF91VPNQbIh1hg7UpXaQAvSTYzYEqdO0maY7n9/DisdWgPD9P14Z9qITLT9WAcva8wVy9jc/qcMGazNrQTrryCwTaZS18uipzOqpqWunoRJITFVLNXp9kztxsZTWSH52/zl4GJlsMeYfQGGeAQFJgSzHQndBH+NIjYLC6SgK5NAaiiCpw0Atqq9EnBw42wH1HQMbeP+0q3jzTaXF++dJZHPFiItZTVLqyorAHYWcxW45Y8KBTllHZpI7eZr7Hkdjc=
  skip_cleanup: true
  on:
    repo: TimothyCole/socialblade-js
    branch: master
