language: node_js
node_js:
- 10.8.0
cache:
  directories:
  - node_modules
install:
- npm install
- npm install -g typescript
script:
- npm test
notifications:
  email: false
before_deploy:
- npm install --production
deploy:
  provider: npm
  email: tim@timcole.me
  api_key:
    secure: uQ+4glqwUZtRLPqsC32nEzmmLDsgq5byw/XskGR63Txpejy86pwqJu9TskVS36zmaOm12HFg2/GlUOv/No/HkhhHTz/jG0Ktt01qXDpgkJhGlokvSu0XhHX8rMx7D8Fof3SBkBpKsoDzCdFVIeVErEb2BGX2UKm8euqvXn/7cxFboFaJRKDma7rHG+KiTOd0llOZh3E7FuBynTQLZHDDMaVGszsNGWdvVxGYQr187IyjaxYSGPF14S6CgIHCFqmvrnlnK/zVVzGEq1wpW0w2Z8kEANshypDhF3Ga3XNM9buJaiRLml9Eh9bUFrHcSq76P6rlwQTGyeVtWMQ7R3vdSztoXMw9wMlHahF7Mw7BJ5nOrBvYGGRSIvME2wBaHvPePW1M+T8UcgzFrI6+K0OK2W8ZhmFbbjL+S2MoG73b8QwEon6p+4UrgW+yPwbmClnjARx4LXKS0/pzPVBsiyA7mGLNdjZMOpurEUvWjsPPgHdCX3xfrn1diwP9hTXmeEPp4rmcZD+2F3eipoykCkPgF+IfDUDdvfNTZ9w0nlqkE9uoTMs/w5t4uSTmURc+uGHbIul1UYA7Vcl8sInRopHKBQ6xQxQ6gNP2iWDwwXF26rmd52CN9eEEPhHTHN0P/qJKhME5VIia1sMusgusfEoPhK1/ENwC3z8MVxXcR/Ed8oo=
  skip_cleanup: true
  on:
    repo: TimothyCole/socialblade-js
    branch: master
